source 'https://rubygems.org'

gem 'cucumber', '>= 1.3.18'
gem 'rspec'
gem 'rake'
gem 'sinatra'
gem 'sinatra-contrib'
gem 'appium_lib'
gem 'appium_console'
gem 'json'
gem 'httparty'
gem 'shotgun'
gem 'tenjin'
