source 'https://rubygems.org'

gem 'cucumber', '>= 2.0.0'
gem 'rspec'
gem 'rake'
gem 'sinatra'
gem 'sinatra-contrib'
gem 'appium_lib'
gem 'appium_console'
gem 'json'
gem 'httparty'
gem 'shotgun'
gem 'tenjin'
gem 'nokogiri'
gem 'rubocop'
